[problems]
[[problems.leetcode]]
name = "2-Sum-Problem"
url = "https://leetcode.com/problems/two-sum/"
number = 1
level = "EASY"
labels = [ "striver", "striver-4",]

[[problems.leetcode]]
name = "Add two numbers as LinkedList"
url = "https://leetcode.com/problems/add-two-numbers/"
number = 2
level = "MEDIUM"
labels = [ "striver", "striver-5",]

[[problems.leetcode]]
name = "Longest Substring without repeat"
url = "https://leetcode.com/problems/longest-substring-without-repeating-characters/"
number = 3
level = "MEDIUM"
labels = [ "striver", "striver-4",]

[[problems.leetcode]]
name = "4-sum-Problem"
url = "https://leetcode.com/problems/4sum/"
number = 18
level = "MEDIUM"
labels = [ "striver", "striver-4",]

[[problems.leetcode]]
name = "Remove N-th node from back of LinkedList"
url = "https://leetcode.com/problems/remove-nth-node-from-end-of-list/"
number = 19
level = "MEDIUM"
labels = [ "striver", "striver-5",]

[[problems.leetcode]]
name = "Merge two sorted Linked List (use method used in mergeSort)"
url = "https://leetcode.com/problems/merge-two-sorted-lists/"
number = 21
level = "EASY"
labels = [ "striver", "striver-5",]

[[problems.leetcode]]
name = "Reverse a LinkedList in groups of size k"
url = "https://leetcode.com/problems/reverse-nodes-in-k-group/"
number = 25
level = "HARD"
labels = [ "striver", "striver-6",]

[[problems.leetcode]]
name = "Next Permutation"
url = "https://leetcode.com/problems/next-permutation/"
number = 31
level = "MEDIUM"
labels = [ "striver", "striver-1",]

[[problems.leetcode]]
name = "Rotate Matrix"
url = "https://leetcode.com/problems/rotate-image/"
number = 48
level = "MEDIUM"
labels = [ "striver", "striver-2",]

[[problems.leetcode]]
name = "Pow(X,n)"
url = "https://leetcode.com/problems/powx-n/"
number = 50
level = "MEDIUM"
labels = [ "striver", "striver-3",]

[[problems.leetcode]]
name = "Kadane's Algorithm"
url = "https://leetcode.com/problems/maximum-subarray/"
number = 53
level = "EASY"
labels = [ "striver", "striver-1",]

[[problems.leetcode]]
name = "Merge Overlapping Subintervals"
url = "https://leetcode.com/problems/merge-intervals/"
number = 56
level = "MEDIUM"
labels = [ "striver", "striver-2",]

[[problems.leetcode]]
name = "Rotate a LinkedList"
url = "https://leetcode.com/problems/rotate-list/description/"
number = 61
level = "MEDIUM"
labels = [ "striver", "striver-6",]

[[problems.leetcode]]
name = "Grid Unique Paths"
url = "https://leetcode.com/problems/unique-paths/"
number = 62
level = "MEDIUM"
labels = [ "striver", "striver-3",]

[[problems.leetcode]]
name = "Set Matrix Zeroes"
url = "https://leetcode.com/problems/set-matrix-zeroes/"
number = 73
level = "MEDIUM"
labels = [ "striver", "striver-1", "LC Patterns", "Arrays"]

[[problems.leetcode]]
name = "Search in a 2d Matrix"
url = "https://leetcode.com/problems/search-a-2d-matrix/"
number = 74
level = "MEDIUM"
labels = [ "striver", "striver-3",]

[[problems.leetcode]]
name = "Sort an array of 0's 1's 2's"
url = "https://leetcode.com/problems/sort-colors/"
number = 75
level = "MEDIUM"
labels = [ "striver", "striver-1",]

[[problems.leetcode]]
name = "Merge two sorted Arrays without extra space"
url = "https://leetcode.com/problems/merge-sorted-array/"
number = 88
level = "EASY"
labels = [ "striver", "striver-2",]

[[problems.leetcode]]
name = "Pascal's Triangle"
url = "https://leetcode.com/problems/pascals-triangle/"
number = 118
level = "EASY"
labels = [ "striver", "striver-1",]

[[problems.leetcode]]
name = "Stock Buy and Sell"
url = "https://leetcode.com/problems/best-time-to-buy-and-sell-stock/"
number = 121
level = "EASY"
labels = [ "striver", "striver-1",]

[[problems.leetcode]]
name = "Longest Consecutive Sequence"
url = "https://leetcode.com/problems/longest-consecutive-sequence/"
number = 128
level = "MEDIUM"
labels = [ "striver", "striver-4",]

[[problems.leetcode]]
name = "Single Number"
url = "https://leetcode.com/problems/single-number/"
number = 136
level = "EASY"
labels = ["LC Patterns", "Arrays", ]

[[problems.leetcode]]
name = "Detect a cycle in Linked List"
url = "https://leetcode.com/problems/linked-list-cycle/"
number = 141
level = "EASY"
labels = [ "striver", "striver-6",]

[[problems.leetcode]]
name = "Find the starting point of the Loop of LinkedList"
url = "https://leetcode.com/problems/linked-list-cycle-ii/"
number = 142
level = "MEDIUM"
labels = [ "striver", "striver-6",]

[[problems.leetcode]]
name = "Find intersection point of Y LinkedList"
url = "https://leetcode.com/problems/intersection-of-two-linked-lists/"
number = 160
level = "EASY"
labels = [ "striver", "striver-6",]

[[problems.leetcode]]
name = "Majority Element (>N/2 times)"
url = "https://leetcode.com/problems/majority-element/"
number = 169
level = "EASY"
labels = [ "striver", "striver-3",]

[[problems.leetcode]]
name = "Reverse a LinkedList"
url = "https://leetcode.com/problems/reverse-linked-list/"
number = 206
level = "EASY"
labels = [ "striver", "striver-5",]

[[problems.leetcode]]
name = "Contains Duplicate"
url = "https://leetcode.com/problems/contains-duplicate/"
number = 217
level = "EASY"
labels = [ "LC Patterns", "Arrays",]

[[problems.leetcode]]
name = "Majority Element (>N/3 times)"
url = "https://leetcode.com/problems/majority-element-ii/"
number = 229
level = "MEDIUM"
labels = [ "striver", "striver-3",]

[[problems.leetcode]]
name = "Check if a LinkedList is palindrome or not"
url = "https://leetcode.com/problems/palindrome-linked-list/"
number = 234
level = "EASY"
labels = [ "striver", "striver-6",]

[[problems.leetcode]]
name = "Delete a given Node when a node is given. (0(1) solution)"
url = "https://leetcode.com/problems/delete-node-in-a-linked-list/"
number = 237
level = "EASY"
labels = [ "striver", "striver-5",]

[[problems.leetcode]]
name = "Product of Array Except Self"
url = "https://leetcode.com/problems/product-of-array-except-self/"
number = 238
level = "MEDIUM"
labels = [ "LC Patterns", "Arrays", ]

[[problems.leetcode]]
name = "Missing Number"
url = "https://leetcode.com/problems/missing-number/"
number = 268
level = "EASY"
labels = [ "LC Patterns", "Arrays", "Bit Manipulation", ]

[[problems.leetcode]]
name = "Find the duplicate in an array of N+1 integers"
url = "https://leetcode.com/problems/find-the-duplicate-number/"
number = 287
level = "MEDIUM"
labels = [ "striver", "striver-2", "LC Patterns", "Arrays"]

[[problems.leetcode]]
name = "Find All Duplicates in an Array"
url = "https://leetcode.com/problems/find-all-duplicates-in-an-array/"
number = 442
level = "MEDIUM"
labels = [ "LC Patterns", "Arrays", ]

[[problems.leetcode]]
name = "Reverse Pairs (Leetcode)"
url = "https://leetcode.com/problems/reverse-pairs/"
number = 493
level = "HARD"
labels = [ "striver", "striver-3",]

[[problems.leetcode]]
name = "Find the middle of LinkedList"
url = "https://leetcode.com/problems/middle-of-the-linked-list/"
number = 876
level = "EASY"
labels = [ "striver", "striver-5",]

[[problems.leetcode]]
name = "Convert 1D Array into 2D Array"
url = "https://leetcode.com/problems/convert-1d-array-into-2d-array/"
number = 2022
level = "EASY"
labels = ["LC Patterns", "Arrays"]

[[problems.interviewbit]]
name = "Repeat and Missing Number"
url = "https://www.interviewbit.com/problems/repeat-and-missing-number-array/"
level = "MEDIUM"
labels = [ "striver", "striver-2",]

[[problems.interviewbit]]
name = "Count number of subarrays with given Xor K"
url = "https://www.interviewbit.com/problems/subarray-with-given-xor/"
level = "MEDIUM"
labels = [ "striver", "striver-4",]

[[problems.codingninjas]]
name = "Inversion of Array (Pre-req: Merge Sort)"
url = "https://www.codingninjas.com/codestudio/problems/count-inversions_615"
level = "MEDIUM"
labels = [ "striver", "striver-2",]

[[problems.geeksforgeeks]]
name = "Largest Subarray with 0 sum"
url = "https://practice.geeksforgeeks.org/problems/largest-subarray-with-0-sum/1"
level = "EASY"
labels = [ "striver", "striver-4",]

[[problems.geeksforgeeks]]
name = "Flattening of a LinkedList"
url = "https://practice.geeksforgeeks.org/problems/flattening-a-linked-list/1"
level = "MEDIUM"
labels = [ "striver", "striver-6",]
