# Generated by Django 2.0.13 on 2019-09-09 05:47

from django.db import migrations
import wagtailmarkdown.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtailmarkdown.fields.MarkdownField(),
        ),
    ]
