name: Publish Github Pages
on:
  push:
    branches: [master]
  workflow_dispatch:
    inputs:
      debug_enabled:
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false

jobs:
  gh-pages:
    name: Publish Github Pages
    runs-on: self-hosted
    steps:
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.debug_enabled }}
    - name: Setup dependencies
      run: |
        add-apt-repository ppa:git-core/ppa -y
        apt-get update
        apt-get install -y --upgrade libffi-dev git curl libssl-dev make build-essential
    - name: Setup Python
      uses: actions/setup-python@v2
    - name: Pull Code
      uses: actions/checkout@master
      with:
        fetch-depth: 0
    - name: Build and Commit
      run: |
        pip install -q --upgrade wheel
        pip install -q -r requirements.txt
        ablog clean
        ablog build
        cp CNAME docs/
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git config --local pull.rebase false
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
