name: Publish Github Pages
on:
  push:
    branches: [master]

jobs:
  gh-pages:
    name: Publish Github Pages
    runs-on: ubuntu-20.04
    steps:
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        fetch-depth: 0
    - name: Build and Commit
      uses: sphinx-notes/pages@v2
      with:
        documentation_path: .
        requirements_path: ./requirements.txt
    - name: Push Changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages
